openapi: 3.0.2
tags:
  - name: Control
    description: Запросы управления
  - name: State
    description: Запросы состояния
info:
  version: '1.0'
  title: Методы работы с ремонтными бригадами
  description: 'Методы работы с ремонтными бригадами'
  contact:
    name: andrwnv
    email: glazynovand@gmail.com
    url: 'https://github.com/andrwnv'
servers:
  - url: 'localhost:5000/api/v2/team'
    description: team
paths:
  /teams:
    get:
      tags:
        - State
      summary: Получение списка ремонтных бригад
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - teams
                properties:
                  teams:
                    type: array
                    x-stoplight:
                      id: zeblpmhyqnauw
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/RepairTeam'
        '429':
          description: Too Many Requests
        5XX:
          description: Server Error
      x-stoplight:
        id: gwwnz76iilgfu
      operationId: get-team-all
      description: Получение списка ремонтных бригад
    parameters: []
  '/{name}':
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
        description: Имя бригады
    get:
      summary: Получение информации о ремонтной бригаде
      tags:
        - State
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepairTeam'
        '404':
          description: Not Found
        '429':
          description: Too Many Requests
        5XX:
          description: Server Error
      operationId: get-team-info
      x-stoplight:
        id: dyuvrk5ofn2fr
      description: Получение информации о ремонтной бригаде
  '/take/{name}':
    post:
      summary: Отправка ремонтной бригаде на объект
      tags:
        - Control
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '409':
          description: Conflict
        '429':
          description: Too Many Requests
        5XX:
          description: Server Error
      operationId: post-team-take
      x-stoplight:
        id: ky2f0oue3392x
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - location
                - item
              properties:
                location:
                  $ref: '#/components/schemas/Location'
                cell_name:
                  type: string
                  x-stoplight:
                    id: h417q04vgllxd
                  description: Опциональное поле уточняющее позицию элемента
                  example: alpha_cell
                item:
                  type: string
                  x-stoplight:
                    id: o0sbgttx3uwt6
                  example: liquid-storage-f8931907-2cc4-4e01-9787-4bc78c780d90
                  description: Над каким элементом необходимо провести работы
      description: Отправка ремонтной бригаде на объект
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
        description: Имя бригады
  '/back/{name}':
    post:
      summary: Отзыв ремонтной бригаде с объекта
      tags:
        - Control
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '409':
          description: Conflict
        '429':
          description: Too Many Requests
        5XX:
          description: Server Error
      operationId: post-team-back
      x-stoplight:
        id: dmwmff9yzkrje
      description: Отзыв ремонтной бригаде с объекта
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
        description: Имя бригады
components:
  schemas:
    RepairTeam:
      title: RepairTeam
      x-stoplight:
        id: kcfsm3yfnpvet
      type: object
      required:
        - name
        - is_busy
        - current_location
        - current_location_item
        - workers
      properties:
        name:
          x-stoplight:
            id: ves4i4c5r28ce
          description: Название комманды
          enum:
            - alpha_team
            - beta_team
            - gamma_team
            - delta_team
            - epsilon_team
          example: alpha_team
        is_busy:
          type: boolean
          x-stoplight:
            id: fzyeh6pk0pk0w
          description: Занята ли комманда в текущий момент времени
        current_location:
          $ref: '#/components/schemas/Location'
        current_location_item:
          type: string
          x-stoplight:
            id: jczq90juc82vh
          description: Над каким элементом проводятся работы
          example: liquid-storage-f8931907-2cc4-4e01-9787-4bc78c780d90
        remaining_rest_time_ms:
          type: integer
          x-stoplight:
            id: 0wq4qtvtgsq8m
          minimum: 0
          default: 0
          example: 1500
          description: Оставшееся время отдыха. Появляется только когда работники в локации `HOME`
        workers:
          x-stoplight:
            id: 6olo9qavr6kb6
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Worker'
      description: Иформация о бригаде
    Worker:
      title: Worker
      x-stoplight:
        id: o4j19kq4c8rpv
      type: object
      description: Информация о работнике
      required:
        - name
        - is_weak
        - is_busy
        - grade
      properties:
        name:
          type: string
          x-stoplight:
            id: 2xk7whzsbbeop
          description: Полное имя работника
          example: Grace Bentley
        is_weak:
          type: boolean
          x-stoplight:
            id: ayofilw8pl69w
          description: Есть ли дебаф на работнике
        is_busy:
          type: boolean
          x-stoplight:
            id: iluwulguma0wu
          description: Занят ли работник
        grade:
          x-stoplight:
            id: 6f3jytx44hsvq
          enum:
            - beginner
            - trainee
            - engineer
            - lead_engineer
          description: Квалификация работника
    Location:
      title: Location
      x-stoplight:
        id: 0nl0mjtni44fw
      enum:
        - energy_system_unit
        - home_unit
        - atmoshpere_unit
      description: Локация в системе
